version = "1.0.0"
owner = "etienne@scalingo.com"
team = "IST"
description = "Buildpack with Cairo (and Pixman and FreeType)"
languages = ["shell"]
destination_server = []
flags = ["buildpack"]
dependencies = []
